version: '3.8'
services:
  ha_resouce_status_exporter:
    restart: always
    build: .
    ports:
      - "9562:9562"
    volumes:
      - ./config/proxmox_ha_status_exporter.yml:/app/config/proxmox_ha_status_exporter.yml