default:
    proxmox_node: 1.2.3.4
    user: user@pve
    password: supersecretpassword
    log_level: info # Optional - Default is info
    verify_ssl: true # Optional - Default is true
    scrape_interval: 60 # Optional - Default is 60